### ISSUE TITLE
Uncaught TypeError: Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by romaan7** [HarryStevens/jeezy#3]
Whenever I try to pass an array which has been initialized with no data BUT contains elements pushed after the initialization I get the below error.

Uncaught TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at Object.s [as max] (jeezy.min.js:62)

**Comment by HarryStevens** [comment]
Can you paste some code so I can reproduce the bug? I tried but couldn't with:
```js
function max(arr){
  return arr.reduce(function(a, b) {
    return Math.max(a, b);
  });
}

var arr = [];
arr.push(8);
arr.push(2);

max(arr); // returns 8
```

**Comment by romaan7** [comment]
Yes, faced this while working on a piece from d3 tutorial at https://bl.ocks.org/HarryStevens/7e3ec1a6722a153a5d102b6c42f4501d
(see attached)

`var names = [];
d3.json("bike_data.json", function(error, bdata) {
    for (i in bdata) {
        names.push(bdata[i].bike_stand);
          }
        });

var y = d3.scaleLinear()
        .rangeRound([20, 0]);

y.domain([0, jz.arr.max(names.map(function(d){ return d.sum }))]);`

[test.zip](https://github.com/HarryStevens/jeezy/files/2876780/test.zip)

**Comment by HarryStevens** [comment]
There were several errors in that code. See below.

```js
var names = [];

d3.json("bike_data.json", function(error, bdata) {
  // Your for loop was invalid. I think that's Python syntax.
  for (var i = 0; i < bdata.length; i++) {
    // You were trying to push the property "bike_stand" but the actual
    // property is called "bike_stands"
    names.push(bdata[i].bike_stands); 
  }

  // The following code was outside of the d3.json callback.
  // You have to be mindful of scoping in JavaScript.
  var y = d3.scaleLinear()
        .rangeRound([20, 0]);

  // Your mapping function was attempting to return a property called sum that was not present
  // in what would have been your names array (if you had been correctly pushing to your names array)
  y.domain([0, jz.arr.max(names)]);
});
```
